CREATE TABLE clubs (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL UNIQUE REFERENCES users(id),
    name VARCHAR(150) NOT NULL,
    city VARCHAR(100) NOT NULL,
    divisions TEXT
);